---
title: "Homework 7 - Intro to working in the shell"
format: docx
editor: visual
---

Fill out [this Quarto document](https://github.com/BIFX552-22/CourseInfo/hw/07intro_to_shell.qmd) while completing the lesson on working in the shell.

To start out, read [Logging into the Hood cluster](https://hood.blackboard.com/bbcswebdav/pid-451170-dt-content-rid-6739862_1/xid-6739862_1).

## [Introducing the Shell](https://datacarpentry.org/shell-genomics/01-introduction/index.html)

::: callout-tip
## Key Points

-   The shell gives you the ability to work more efficiently by using keyboard commands rather than a GUI.

-   Useful commands for navigating your file system include: ls, pwd, and cd.

-   Most commands take options (flags) which begin with a -.

-   Tab completion can reduce errors from mistyping and make work more efficient in the shell.
:::

Once you have logged into the cluster, enter the following commands to set up your working directory for this lesson. If you prefer to work locally, you can fetch the data from [figshare](https://figshare.com/articles/dataset/Data_Carpentry_Genomics_beta_2_0/7726454).

    # assuming you are working from your home directory
    scp /BIODATA/BIFX552/shell_data.tar.gz .
    tar -xf shell_data.tar.gz
    rm shell_data.tar.gz

#### Challenge

Use the `-l` option for the `ls` command to display more information for each item in the directory. What is one piece of additional information this long format gives you that you don't see with the bare `ls` command?

    -bash-4.2$ ls -l
    total 8
    drwxr-xr--. 2 1024 users 4096 Oct 13 17:51 sra_metadata
    drwxr-xr-x. 2 1024 users 4096 Oct 13 17:51 untrimmed_fastq

## [Navigating Files and Directories](https://datacarpentry.org/shell-genomics/02-the-filesystem/index.html)

::: callout-tip
### Key Points

-   The `/`, `~`, and `..` characters represent important navigational shortcuts.
-   Hidden files and directories start with `.` and can be viewed using `ls -a`.
-   Relative paths specify a location starting from the current location, while absolute paths specify a location from the root of the file system.
:::

#### Challenge - Finding hidden directories

First navigate to the `shell_data` directory. There is a hidden directory within this directory. Explore the options for `ls` to find out how to see hidden directories. List the contents of the directory and identify the name of the text file in that directory.

Hint: hidden files and folders in Unix start with `.`, for example `.my_hidden_directory`.

    -bash-4.2$ pwd
    /home/ijl1/shell_data
    -bash-4.2$ ls -a
    .  ..  .hidden  sra_metadata  untrimmed_fastq

#### Challenge - Navigating practice

Navigate to your home directory. From there, list the contents of the `untrimmed_fastq` directory.

    -bash-4.2$ ls -F
    SRR097977.fastq  SRR098026.fastq

    -bash-4.2$ pwd
    /home/ijl1
    -bash-4.2$ ls shell_data/untrimmed_fastq
    SRR097977.fastq  SRR098026.fastq

#### Challenge - Relative path resolution

Using the filesystem diagram below, if `pwd` displays `/Users/thing`, what will `ls ../backup` display?

-   `../backup: No such file or directory`
-   `2012-12-01 2013-01-08 2013-01-27`
-   `2012-12-01/ 2013-01-08/ 2013-01-27/`
-   `original pnas_final pnas_sub - this is what we will see`

## [Working with Files and Directories](https://datacarpentry.org/shell-genomics/03-working-with-files/index.html)

::: callout-tip
### Key Points

-   You can view file contents using `less`, `cat`, `head` or `tail`.
-   The commands `cp`, `mv`, and `mkdir` are useful for manipulating existing files and creating new directories.
-   You can view file permissions using `ls -l` and change permissions using `chmod`.
-   The history command and the up arrow on your keyboard can be used to repeat recently used commands.
:::

#### Challenge 1

Do each of the following tasks from your current directory using a single `ls` command for each:

\- List all of the files in \`/usr/bin\` that start with the letter 'c'

    -bash-4.2\$ ls /usr/bin/c\*

\- List all of the files in \`/usr/bin\` that contain the letter 'a'.

    -bash-4.2\$ ls /usr/bin/\*a\*

\- List all of the files in \`/usr/bin\` that end with the letter 'o'.

    -bash-4.2\$ ls /usr/bin/\*o

\- Bonus: List all of the files in \`/usr/bin\` that contain the letter 'a' or the letter 'c'.

    ls /usr/bin/\*\[ac\]\*

Hint: The bonus question requires a Unix wildcard that we haven't talked about yet. Try searching the internet for information about Unix wildcards to find what you need to solve the bonus problem.

#### Challenge 2

`echo` is a built-in shell command that writes its arguments, like a line of text to standard output. The echo command can also be used with pattern matching characters, such as wildcard characters. Here we will use the `echo` command to see how the wildcard character is interpreted by the shell.

        $ echo *.fastq
        SRR097977.fastq SRR098026.fastq

The `*` is expanded to include any file that ends with `.fastq`. We can see that the output of `echo *.fastq` is the same as that of `ls *.fastq`.

What would the output look like if the wildcard could not be matched? Compare the outputs of `echo *.missing` and `ls *.missing`.

    -bash-4.2$ echo *.missing
    *.missing
    -bash-4.2$ ls *.missing
    ls: cannot access *.missing: No such file or directory

#### Challenge 3

Find the line number in your history for the command that listed all the .sh files in `/usr/bin`. Rerun that command.

       64  ls /usr/bin/*.sh
       65  history
    -bash-4.2$ !64
    ls /usr/bin/*.sh
    /usr/bin/amuFormat.sh  /usr/bin/lprsetup.sh          /usr/bin/unix-lpr.sh
    /usr/bin/gettext.sh    /usr/bin/rescan-scsi-bus.sh
    /usr/bin/lesspipe.sh   /usr/bin/setup-nsssysinit.sh


    -bash-4.2$ history | grep *.sh
       64  ls /usr/bin/*.sh
       66  ls /usr/bin/*.sh
       73  history | grep *.sh

#### Challenge 4

-   Print out the contents of the `~/shell_data/untrimmed_fastq/SRR097977.fastq` file. What is the last line of the file?

```{=html}
<!-- -->
```
    cat ~/shell_data/untrimmed_fastq/SRR097977.fastq
    C:CCC::CCCCCCCC<8?6A:C28C<608'&&&,'$

    less ~/shell_data/untrimmed_fastq/SRR097977.fastq
    C:CCC::CCCCCCCC<8?6A:C28C<608'&&&,'$

From your home directory, and without changing directories, use one short command to print the contents of all of the files in the `~/shell_data/untrimmed_fastq` directory.

    # insert *only code* here (output not needed for this one)
    cat ~/shell_data/untrimmed_fastq/*

#### Challenge 5

What are the next three nucleotides (characters) after the first instance of the sequence, `TTTTT`?

    less SRR097977.fastq
    /TTTTT #search in less
    #next three letters were CAC after the first instance of the sequence

#### Challenge 6

Starting in the `shell_data/untrimmed_fastq/` directory, do the following:

-   Make sure that you have deleted your backup directory and all files it contains.
-   Create a backup of each of your FASTQ files using `cp`. (Note: You'll need to do this individually for each of the two FASTQ files. We haven't learned yet how to do this with a wildcard.)scp
-   Use a wildcard to move all of your backup files to a new backup directory.
-   Change the permissions on all of your backup files to be write-protected.

    -bash-4.2$ mkdir backup
    -bash-4.2$ scp *.fastq backup/.
    -bash-4.2$ chmod -w backup/*
    -bash-4.2$ ls -l backup/
    total 92
    -r--r--r--. 1 1024 users 47552 Oct 13 20:15 SRR097977.fastq
    -r--r--r--. 1 1024 users 43332 Oct 13 20:15 SRR098026.fastq
    -bash-4.2$ 
